services:
  jenkins-controller:
    build:
      context: .
      dockerfile: jenkins.Dockerfile
    environment:
      - CASC_JENKINS_CONFIG=/jenkins.yml
      - CASC_RELOAD_TOKEN=$CASC_RELOAD_TOKEN
      - JAVA_ARGS='-Djava.awt.headless=true -Dhudson.model.DirectoryBrowserSupport.CSP="default-src 'self' 'unsafe-inline' 'unsafe-eval'; img-src 'self' 'unsafe-inline' data:;"'
    volumes:
      - ./jenkins.yml:/jenkins.yml
      - ./id_rsa:/secrets/id_rsa
      - ./adminpassword:/secrets/adminpassword
      - /home/jenkins/jenkins-data:/var/jenkins_home
    ports:
      - 8080:8080
  jenkins-agent:
    env_file: ./agent.env
    build:
      context: .
      dockerfile: jenkins-agent.Dockerfile
      args:
        DOCKER_GROUP: '${DOCKER_GROUP}'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
